# This is an example configuration file
# To learn more, see the full config.yaml reference: https://docs.continue.dev/reference

name: Example Config
version: 1.0.0
schema: v1

# Define which models can be used
models:
  - name: qwen2.5-coder:7b
    provider: ollama
    model: qwen2.5-coder:7b 

  - name: qwen2.5-coder:7b
    provider: ollama
    model: qwen2.5-coder:7b
    roles: 
      - autocomplete
    autocompleteOptions:
      debounceDelay: 300
      maxPromptTokens: 2048
      onlyMyCode: true
    defaultCompletionOptions:
      temperature: 0.3
  - name: nomic-embed-text:latest
    provider: ollama
    model: nomic-embed-text:latest
    roles:
      - embed
